#!/bin/bash

set -euo pipefail
trap 'rc=$?;set +ex;if [[ $rc -ne 0 ]];then trap - ERR EXIT;echo 1>&2;echo "*** fail *** : code $rc : $DIR/$SCRIPT $ARGS" 1>&2;echo 1>&2;exit $rc;fi' ERR EXIT
ARGS="$*"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$(basename "${BASH_SOURCE[0]}")"

# see /etc/sysctl.d/local.conf for setting of net.ipv4.ip_unprivileged_port_start

set -x
exec podman run -it --rm  --cap-add SYS_ADMIN --cap-add NET_ADMIN -v ${DIR}:/sandbox -p 2222:22 -p 53:53/udp -p 53:53 -p 80:80 -h shed.tiny.hodain.net --name sandbox sandbox
